/** Operation portal copy — doc 14 names the cards, the columns, the filters and the flows. */
export const OPS = {
  portal: 'Operation Dashboard',
  brand: 'PRsystem',
  realm: 'Realm: Operation/Platform',
  signInTitle: 'Operation portal-д нэвтрэх',
  code: 'Authenticator код (6 орон)',
  stepUpTitle: 'Step-up баталгаажуулалт',
  stepUpHint: 'Энэ үйлдэлд сүүлийн 10 минутын дотор хийсэн хоёр дахь баталгаажуулалт шаардлагатай.',
  stepUp: 'Баталгаажуулах',
  nav: {
    dashboard: 'Dashboard',
    subscriptions: 'Буудлын subscription',
    onboarding: 'Onboarding queue',
    reconciliations: 'Paid reconciliation',
    recovery: 'Account recovery',
    accounts: 'Operation хэрэглэгч',
    sms: 'SMS сануулга',
  },
  kpi: {
    title: 'Canonical KPI',
    asOf: 'as_of',
    totalHotels: 'Нийт буудал',
    active: 'Идэвхтэй',
    expiringSoon: 'Удахгүй дуусна',
    grace: 'Grace period',
    expired: 'Дууссан',
    suspended: 'Түдгэлзсэн',
    inactive: 'Идэвхжээгүй',
    P20: '20,000₮',
    P25: '25,000₮',
    P30: '30,000₮',
    smsSent: 'SMS Илгээсэн',
    smsDelivered: 'SMS Хүрсэн',
    smsFailed: 'SMS Амжилтгүй',
  },
  list: {
    title: 'Буудлын subscription жагсаалт',
    filters: 'Filter ба хайлт',
    name: 'Буудлын нэр',
    phone: 'Subscription contact утас',
    email: 'Бүртгэлтэй email',
    ownerType: 'Бүртгэлийн төрөл',
    district: 'Дүүрэг',
    package: 'Багц',
    termMonths: 'Сонгосон хугацаа',
    status: 'Subscription төлөв',
    expiresFrom: 'Дуусах огноо — эхлэх',
    expiresTo: 'Дуусах огноо — дуусах',
    any: 'Бүгд',
    columns: {
      n: '№',
      hotelName: 'Буудлын нэр',
      ownerType: 'Бүртгэлийн төрөл',
      district: 'Дүүрэг/хаяг',
      contactPhone: 'Contact утас',
      emailMasked: 'Email',
      package: 'Багц',
      termMonths: 'Хугацаа (сар)',
      startsAt: 'Эрх эхэлсэн',
      expiresAt: 'Эрх дуусах',
      remainingDays: 'Үлдсэн хоног',
      status: 'Төлөв',
      actions: 'Үйлдэл',
    },
    details: 'Дэлгэрэнгүй',
    sendSms: 'SMS илгээх',
    passwordReset: 'Password reset',
    ownerTypes: { ORGANIZATION: 'Байгууллага', CITIZEN: 'Хувь хүн' } as Record<string, string>,
    statuses: {
      ACTIVE: 'Идэвхтэй',
      EXPIRING_SOON: 'Удахгүй дуусна',
      GRACE: 'Grace period',
      EXPIRED: 'Дууссан',
      SUSPENDED: 'Түдгэлзсэн',
    } as Record<string, string>,
  },
  detail: {
    title: 'Subscription',
    history: 'Suspension түүх',
    suspend: 'Түдгэлзүүлэх',
    reactivate: 'Сэргээх',
    reasonCode: 'Reason code',
    note: 'Тэмдэглэл (10–1000, заавал)',
    reset: 'Нууц үг сэргээх хүсэлт илгээх',
    resetHint:
      'Reset холбоос зөвхөн бүртгэлтэй (маскласан) email рүү илгээгдэнэ; холбоос, код энд харагдахгүй.',
    resetQueued: 'Илгээгдсэн',
    resetFailed: 'Илгээхэд алдаа гарсан',
    occurredAt: 'Огноо/цаг',
    suspended: 'Suspended',
  },
  onboarding: {
    title: 'Onboarding application queue',
    group: 'Бүлэг',
    UNPAID: 'Төлбөр баталгаажаагүй',
    INACTIVE: 'Идэвхжээгүй',
    columns: {
      hotelName: 'Буудлын нэр',
      state: 'Application төлөв',
      ownerType: 'Бүртгэлийн төрөл',
      district: 'Дүүрэг',
      package: 'Багц',
      termMonths: 'Хугацаа',
      emailMasked: 'Email',
      createdAt: 'Үүссэн',
      attempts: 'Provision оролдлого',
    },
  },
  reconciliations: {
    title: 'Paid reconciliation queue',
    hint: 'Автоматаар apply болоогүй paid record. Terminal outcome-ийг зөвхөн SUBSCRIPTION_PAYMENT_RECONCILE эрхтэй хэрэглэгч сонгоно.',
    columns: {
      subject: 'Subject',
      provider: 'Provider',
      invoice: 'Invoice',
      payment: 'Payment',
      amount: 'Дүн',
      confirmedAt: 'Баталгаажсан',
      state: 'Төлөв',
    },
  },
  recovery: {
    title: 'Email-д хандах боломжгүй account recovery',
    hint: 'Operation хэрэглэгч зөвхөн support хүсэлтийг бүртгэж Platform Super Admin руу шилжүүлнэ.',
    hotelId: 'Hotel ID',
    caseReference: 'Case reference',
    note: 'Тэмдэглэл (10–1000)',
    escalate: 'Recovery хүсэлт бүртгэх',
    pending: 'Нээлттэй хүсэлтүүд',
    decide: 'Шийдвэрлэх',
    decision: 'Шийдвэр',
    APPROVED: 'Батлах',
    REFUSED: 'Татгалзах',
    reason: 'Шалтгаан (10–1000)',
    columns: {
      requestId: 'Хүсэлт',
      account: 'Account',
      state: 'Төлөв',
      caseReference: 'Case',
      requestedAt: 'Огноо',
    },
  },
  accounts: {
    title: 'Operation хэрэглэгч үүсгэх',
    hint: 'Нэрлэсэн account бүрт explicit permission олгоно; role нэр өөрөө эрх өгөхгүй.',
    email: 'Имэйл',
    role: 'Role',
    permissions: 'Permission нэрс (таслалаар)',
    create: 'Үүсгэх',
    created: 'Account үүсч, enrolment холбоос илгээгдлээ.',
  },
  sms: {
    title: 'SMS сануулга',
    recipients: 'Хүлээн авагч сонгох',
    hotelIds: 'Буудлын ID (таслалаар)',
    body: 'Текст (1–300 тэмдэгт)',
    preview: 'Preview үзэх',
    previewTitle: 'Preview',
    characters: 'Тэмдэгт',
    alphabet: 'Alphabet',
    segments: 'Segment / хүлээн авагч',
    recipientCount: 'Хүлээн авагч',
    duplicateCount: 'Давхардсан',
    excludedCount: 'Хасагдсан дугаар',
    totalSegments: 'Нийт segment',
    estimatedCost: 'Тооцоолсон зардал',
    expiresAt: 'Preview хүчинтэй',
    confirm: 'Илгээхийг баталгаажуулах',
    confirmed: 'Send job үүслээ.',
    history: 'SMS түүх',
    refresh: 'Хүргэлтийн төлөв шинэчлэх',
    columns: {
      jobId: 'Job ID',
      confirmedAt: 'Баталгаажуулсан',
      dispatchedAt: 'Илгээсэн',
      recipients: 'Хүлээн авагч',
      excluded: 'Хасагдсан',
      segments: 'Segment',
      pending: 'Хүлээгдэж буй',
      sent: 'Илгээсэн',
      delivered: 'Хүрсэн',
      failed: 'Амжилтгүй',
      provider: 'Provider ref',
      state: 'Төлөв',
    },
  },
} as const;
