/** Guest portal copy — doc 09 §3 names the screens and their controls. */
export const GUEST = {
  portal: 'Online Booking', // doc 09 title
  brand: 'PRsystem',
  home: 'Нүүр хуудас',
  search: {
    title: 'Буудал хайх',
    checkIn: 'Check-in өдөр',
    checkOut: 'Check-out өдөр',
    location: 'Байршил (хот/дүүрэг/хаяг)',
    useMyLocation: 'Миний одоогийн байршлыг ашиглах',
    locationWhy:
      'Одоогийн координатыг зөвхөн ойрхон буудал тооцоход ашиглана; байнгын хөдөлгөөнийг хянахгүй.',
    locationDenied: 'Байршлын зөвшөөрөл өгөөгүй тул гараар сонгож хайна уу.',
    submit: 'Буудал хайх',
  },
  card: {
    from: '₮-с',
    perNight: 'нэг шөнийн үнэ',
    total: 'нийт',
    call: 'Залгах',
    details: 'Дэлгэрэнгүй үзэх',
    reviews: 'сэтгэгдэл',
    distance: 'зай',
  },
  availability: {
    AVAILABLE: 'Боломжтой',
    FULL: 'Дүүрсэн',
    NOT_TAKING: 'Online захиалга авахгүй',
    NOT_BOOKING: 'Online захиалга авахгүй',
  } as Record<string, string>,
  detail: {
    address: 'Хаяг',
    phone: 'Холбоо барих утас',
    rating: 'Дундаж үнэлгээ',
    categories: 'Боломжит өрөөний ангиллууд',
    book: 'Захиалах',
    reviews: 'Нийтлэгдсэн сэтгэгдлүүд',
    leaveReview: 'Үнэлгээ, сэтгэгдэл үлдээх',
    nights: 'хоног',
    availableRooms: 'боломжтой өрөө',
    stayingGuestName: 'Байрлах зочны нэр',
    provider: 'Төлбөрийн үйлчилгээ',
    confirmTitle: 'Захиалгын баталгаажуулалт',
    unitPrice: 'Нэгж үнэ',
    roomTotal: 'Нийт өрөөний төлбөр',
    cancellation: 'Цуцлалтын нөхцөл',
    cancellationText:
      'Check-in-ээс 24+ цагийн өмнө цуцалбал бүтэн refund; 24 цагаас дотогш болон no-show үед эхний шөнийн төлбөр суутгагдана.',
  },
  auth: {
    signInTitle: 'Утасны дугаараар нэвтрэх',
    registerTitle: 'Утасны дугаараар бүртгүүлэх',
    phone: 'Утасны дугаар',
    password: 'Нууц үг',
    code: '6 оронтой код',
    sendCode: 'Код илгээх',
    codeSent: 'Код илгээгдлээ. Хугацаа дуустал оруулна уу.',
    register: 'Бүртгүүлэх',
    signIn: 'Нэвтрэх',
    signOut: 'Гарах',
    orRegister: 'Шинэ хэрэглэгч бол бүртгүүлнэ үү.',
    orSignIn: 'Бүртгэлтэй бол нэвтэрнэ үү.',
    emongolia: 'e-Mongolia-аар нэвтрэх',
    emongoliaClosed: 'e-Mongolia одоогоор нээлттэй биш; утасны дугаараар бүртгүүлнэ үү.',
  },
  bookings: {
    title: 'Миний захиалгууд',
    ref: 'Захиалгын дугаар',
    hotel: 'Буудал',
    category: 'Өрөөний ангилал',
    dates: 'Check-in / Check-out',
    total: 'Нийт төлбөр',
    booking: 'Захиалга',
    payment: 'Төлбөр',
    refund: 'Буцаалт',
    hold: 'Hold',
    holdUntil: 'Hold дуусах',
    pay: 'Төлбөр төлөх',
    payLink: 'Төлбөрийн холбоос нээх',
    cancel: 'Захиалга цуцлах',
    switchProvider: 'Төлбөрийн үйлчилгээ солих',
    none: 'Захиалга байхгүй байна.',
  },
  states: {
    HOLDING: 'Hold',
    CONFIRMED: 'Баталгаажсан',
    CHECKED_IN: 'Check-in хийсэн',
    COMPLETED: 'Дууссан',
    EXPIRED: 'Хугацаа дууссан',
    CANCELLED_GUEST: 'Зочин цуцалсан',
    CANCELLED_HOTEL: 'Буудал цуцалсан',
    NO_SHOW: 'No-show',
    PENDING: 'Хүлээгдэж байгаа',
    PAID: 'Төлсөн',
    FAILED: 'Амжилтгүй',
    NONE: '—',
    REQUIRED: 'Шаардлагатай',
    REFUNDED: 'Буцаагдсан',
    PARTIALLY_REFUNDED: 'Хэсэгчлэн буцаагдсан',
  } as Record<string, string>,
  review: {
    rating: 'Үнэлгээ (1–5 од)',
    comment: 'Сэтгэгдэл (10–1000 тэмдэгт)',
    submit: 'Илгээх',
  },
} as const;
