/** Police portal copy — doc 13 names the screens, the states and the controls. */
export const POLICE = {
  portal: 'Police',
  brand: 'PRsystem',
  realm: 'Realm: Police',
  signInTitle: 'Police portal-д нэвтрэх',
  nav: {
    dashboard: 'Dashboard',
    matches: 'Match шалгах',
    checkIns: 'Check-in зочдын жагсаалт',
    wanted: 'Шинэ эрэн сурвалжлах бүртгэл',
    exports: 'Wanted Case Excel',
  },
  dashboard: {
    title: 'Dashboard',
    window: 'Хугацааны интервал',
    from: 'Эхлэх',
    to: 'Дуусах',
    activeWantedPeople: 'Идэвхтэй эрэн сурвалжлагдаж буй хүн',
    activeCases: 'Идэвхтэй Wanted Case',
    matchedPeople: 'Match болсон хүн',
    matchEvents: 'Match event',
    foundPeople: 'Олдсон хүн',
    falseMatches: 'Худал Match',
    openMatches: 'Нээлттэй Match',
    charts: 'Police Admin график',
    foundByCategory: 'Олдсон хүмүүс — гэмт хэргийн ангиллаар',
    matchesByHotelDistrict: 'Match/Олдсон — буудлын дүүргээр',
    wantedByHomeDistrict: 'Эрэн сурвалжлагдаж буй — гэрийн хаягийн дүүргээр',
    unknownDistrict: 'Тодорхойгүй',
  },
  search: {
    title: 'Олдсон гэж батлах — active Match нээх',
    hint: 'Бүтэн регистрийн дугаар эсвэл Match ID-г яг тэнцүү оруулна. Хэсэгчилсэн хайлт байхгүй.',
    registrationNumber: 'Регистрийн дугаар',
    matchId: 'Match ID',
    submit: 'Match нээх',
    none: 'Active Match олдсонгүй.',
  },
  match: {
    title: 'Match',
    workflow: 'Workflow төлөв',
    outcome: 'Outcome',
    hotel: 'Буудал',
    district: 'Дүүрэг',
    address: 'Хаяг',
    room: 'Өрөө',
    detectedAt: 'Match илэрсэн (серверийн цаг)',
    checkInRecordedAt: 'Check-in бүртгэсэн',
    actualCheckInAt: 'Бодит check-in',
    firstAcknowledged: 'Анх хүлээн авсан',
    nobodyYet: 'Хэн ч хүлээн аваагүй',
    pendingReview: 'Худал Match хүсэлт хүлээгдэж байна',
    cases: 'Холбоотой Wanted Case',
    acknowledge: 'Хүлээн авсан',
    acknowledgeHint: 'Alert-ийг харж авсны бүртгэл. Хүнийг олсон гэсэн утгагүй.',
    found: 'Олдсон',
    foundTitle: 'Олдсон баталгаажуулалт',
    foundHint: 'Зөвхөн өөрөө бодитоор илрүүлсэн бол өөрийн account-аар батална.',
    locationKind: 'Илрүүлсэн байршлын төрөл',
    atMatchHotel: 'Match гарсан буудалд',
    otherLocation: 'Өөр байршилд',
    locationNote: 'Илрүүлсэн байршлын товч мэдээлэл (Өөр байршилд бол заавал)',
    taskReference: 'Ажиллагаа/даалгаврын дугаар (сонголттой)',
    note: 'Товч тэмдэглэл (сонголттой)',
    falseMatch: 'Худал Match хүсэлт',
    falseMatchHint: 'Хоёр дахь хүн шийдвэрлэх хүртэл outcome өөрчлөгдөхгүй.',
    reasonCode: 'Шалтгааны код',
    reasonNote: 'Тайлбар (10–500 тэмдэгт)',
    revision: 'Revision',
  },
  workflow: {
    NEW: 'Шинэ',
    ACKNOWLEDGED: 'Хүлээн авсан',
    UNDER_REVIEW: 'Шалгаж байгаа',
    RESOLVED: 'Шийдвэрлэсэн',
  } as Record<string, string>,
  outcome: {
    NONE: '—',
    FOUND: 'Олдсон',
    FALSE_MATCH: 'Худал Match',
    LOCATION_STALE: 'Байршил хуучирсан',
  } as Record<string, string>,
  falseMatchReasons: {
    WRONG_NUMBER_ENTERED: 'Регистр буруу оруулсан',
    IDENTIFIER_USED_BY_ANOTHER: 'Регистрийг өөр хүн ашигласан',
    IDENTITY_DISPROVED: 'Identity няцаагдсан',
    OTHER_VERIFIED_REASON: 'Бусад баталгаажсан шалтгаан',
  } as Record<string, string>,
  checkIns: {
    title: 'Бүх буудлын check-in үндсэн зочдын жагсаалт',
    hint: 'Анх нээхэд зөвхөн идэвхтэй stay-ууд. Түүхэн хайлтад интервал (31 хоног хүртэл) ба шалтгаан заавал.',
    from: 'Эхлэх огноо/цаг',
    to: 'Дуусах огноо/цаг',
    reason: 'Хайлтын шалтгаан',
    submit: 'Хайх',
    historical: 'Түүхэн хайлт',
    active: 'Идэвхтэй stay',
    columns: {
      rowNumber: '№',
      hotelName: 'Буудлын нэр',
      district: 'Дүүрэг',
      familyName: 'Овог',
      givenName: 'Нэр',
      registrationNumber: 'Регистрийн дугаар',
      roomNumber: 'Өрөө',
      checkInAt: 'Check-in огноо/цаг',
      plannedCheckoutAt: 'Төлөвлөсөн check-out',
      stayType: 'Stay төрөл',
      source: 'Бүртгэлийн суваг',
      stayState: 'Stay төлөв',
    },
    stayType: { NIGHT: 'Хоног', HOUR: 'Цаг' } as Record<string, string>,
    source: { WALK_IN: 'Walk-in', ONLINE: 'Online' } as Record<string, string>,
  },
  wanted: {
    title: 'Шинэ эрэн сурвалжлах бүртгэл',
    hint: 'Регистрийн дугаараар ХУР-аас identity татна. ХУР олдохгүй бол гараар оруулна (§6.2).',
    registrationNumber: 'Регистрийн дугаар',
    manual: 'ХУР олдохгүй/ажиллахгүй үед гараар оруулах',
    manualReason: 'Гараар оруулах шалтгаан',
    XYP_NOT_FOUND: 'ХУР-аас олдсонгүй',
    XYP_UNAVAILABLE: 'ХУР ажиллахгүй байна',
    familyName: 'Ургийн овог',
    parentName: 'Эцэг/эхийн нэр',
    givenName: 'Өөрийн нэр',
    dateOfBirth: 'Төрсөн он, сар, өдөр',
    homeAddress: 'Гэрийн хаяг',
    homeDistrict: 'Гэрийн хаягийн дүүрэг',
    caseTitle: 'Wanted Case',
    reasonText: 'Эрэн сурвалжлах үндэслэл/холбогдох хэргийн товч тайлбар (10–2000)',
    crimeCategory: 'Гэмт хэргийн ангилал',
    owningUnitRef: 'Харьяалах нэгж',
    submit: 'Хадгалах',
    person: 'Wanted Person',
    provenance: { XYP_VERIFIED: 'ХУР баталгаажсан', MANUAL: 'Гараар оруулсан' } as Record<
      string,
      string
    >,
    approval: {
      PENDING_APPROVAL: 'Identity батлагдаагүй',
      APPROVED: 'Identity батлагдсан',
    } as Record<string, string>,
  },
  cases: {
    title: 'Wanted Case',
    state: 'Case төлөв',
    category: 'Гэмт хэргийн ангилал',
    unit: 'Харьяалах нэгж',
    activatedAt: 'Идэвхжсэн',
    move: 'Төлөв өөрчлөх',
    to: 'Шинэ төлөв',
    reason: 'Шалтгаан (заавал, 5–500)',
    expectedRevision: 'Revision',
    identity: 'Manual identity батлах',
    revisionId: 'Identity revision ID',
    approve: 'Батлах',
    reject: 'Татгалзах',
    swept: 'Идэвхжүүлэх үед шалгасан stay',
  },
  caseStates: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED',
  } as Record<string, string>,
  exports: {
    title: 'Wanted Case Excel export',
    hint: 'Анхдагч export-д регистр масклагдсан. Бүтэн регистр зөвхөн нэмэлт permission, step-up болон зорилго/даалгаврын дугаартай үед.',
    purpose: 'Зорилго (10–500)',
    taskReference: 'Хэрэг/даалгаврын дугаар',
    state: 'Case төлөв (сонголттой)',
    fullIdentifier: 'Бүтэн регистрийн дугаартай',
    run: 'Export үүсгэх',
    job: 'Export ажил',
    rows: 'Мөрийн тоо',
    download: 'Татах холбоос авах (5 минут)',
    expires: 'Файл хадгалагдах хугацаа',
  },
} as const;
