/**
 * Hotel portal copy, taken from the requirement documents.
 *
 * Tabs: doc 02 §5. Room card: doc 06 §2–§3. Cleaner lists and states: doc 04
 * §3, §6. Subscription states: doc 14 §4. Anything the documents do not name
 * is the plainest phrasing and is marked `// unnamed`.
 */
export const HOTEL = {
  portal: 'Reception (RC) System', // doc 02 title
  brand: 'PRsystem',
  signInTitle: 'Зочид буудлын системд нэвтрэх', // unnamed
  chooseHotel: 'Буудал сонгох', // unnamed
  tabs: {
    guests: 'Зочин бүртгэл',
    rooms: 'Өрөөнүүд',
    billing: 'Төлбөр тооцоо',
    restaurant: 'Restaurant',
    cleaner: 'Cleaner dashboard',
    housekeeping: 'Цэвэрлэгээний төлөв',
    shifts: 'Ээлж',
    subscription: 'Subscription',
    staff: 'Ажилтнууд',
    finance: 'Санхүү',
    registry: 'Зочдын жагсаалт',
    catalog: 'Тариф ба өрөө',
  },
  occupancy: {
    VACANT: 'Сул',
    CHECKED_IN: 'Check-in хийсэн',
    CHECKOUT_IN_PROGRESS: 'Check-out хийгдэж байгаа',
  } as Record<string, string>,
  source: { NOT_APPLICABLE: 'Хамаарахгүй', WALK_IN: 'Walk-in', ONLINE: 'Online' } as Record<
    string,
    string
  >,
  stayType: { HOURLY: 'Цагаар', NIGHTLY: 'Хоногоор' } as Record<string, string>,
  timeState: {
    UPCOMING: 'Удахгүй эхэлнэ',
    IN_PROGRESS: 'Үргэлжилж байна',
    ENDING_SOON: 'Дуусах дөхсөн',
    OVERDUE: 'Хугацаа хэтэрсэн',
  } as Record<string, string>,
  cleaning: {
    CLEAN: 'Цэвэр',
    NEEDS_CLEANING: 'Цэвэрлэгээ шаардлагатай',
    CLEANING: 'Цэвэрлэж байгаа',
  } as Record<string, string>,
  minibar: {
    NOT_APPLICABLE: 'Хамаарахгүй',
    FULL: 'Бүтэн',
    SHORT: 'Дутуу',
    UNKNOWN: 'Тодорхойгүй',
  } as Record<string, string>,
  lifecycle: {
    ACTIVE: 'Идэвхтэй',
    RETIRING: 'Идэвхгүй болгохоор хүлээгдэж буй',
    INACTIVE: 'Идэвхгүй',
  } as Record<string, string>,
  subscriptionState: {
    ACTIVE: 'Идэвхтэй',
    EXPIRING_SOON: 'Удахгүй дуусна',
    GRACE: 'Grace period',
    EXPIRED: 'Дууссан',
    SUSPENDED: 'Түдгэлзсэн',
  } as Record<string, string>,
  packages: { P20: '20,000₮', P25: '25,000₮', P30: '30,000₮' } as Record<string, string>,
  cleanerLists: {
    refill: 'Идэвхтэй байрлалтын minibar нөхөх',
    inspect: 'Минибар шалгах',
    clean: 'Цэвэрлэх ба минибар нөхөх',
    reconcile: 'Minibar configuration тааруулах',
  },
  cleanerTaskState: {
    OPEN: 'Хүлээгдэж байгаа',
    PENDING: 'Хүлээгдэж байгаа',
    CLAIMED: 'Гүйцэтгэж байгаа',
    IN_PROGRESS: 'Гүйцэтгэж байгаа',
    INSPECTING: 'Шалгаж байгаа',
    SUBMITTED: 'Илгээсэн',
    RETURNED: 'Залруулах шаардлагатай',
    RESUBMITTED: 'Дахин илгээсэн',
    LOCKED: 'Төлбөрт түгжигдсэн',
    SETTLED: 'Тооцоонд орсон',
    COMPLETED: 'Дууссан',
    IMPOSSIBLE: 'Гүйцэтгэх боломжгүй',
    CANCELLED: 'Цуцлагдсан',
    STOCK_SHORT: 'Нөөц хүрэлцэхгүй',
    VARIANCE: 'Зөрүү шийдэх шаардлагатай',
    ROLLBACK_REQUIRED: 'Rollback шаардлагатай',
  } as Record<string, string>,
  actions: {
    claim: 'Ажлыг авах',
    complete: 'Дуусгах',
    noUsage: 'Минибар хэрэглээгүй',
    submitReport: 'Тайлан илгээх',
    impossible: 'Гүйцэтгэх боломжгүй',
    startCheckout: 'Check-out эхлүүлэх',
    cancelCheckout: 'Check-out цуцлах',
    finishCheckout: 'Check-out дуусгах',
    checkIn: 'Check-in хийх',
    quote: 'Үнийн санал авах',
    openShift: 'Ээлж нээх',
    countShift: 'Бэлэн мөнгө тоолох',
    closeShift: 'Ээлж хаах',
    recordPayment: 'Төлбөр бүртгэх',
    settle: 'Тооцоо хаах',
    issueGuestCode: 'Guest access код үүсгэх',
    revokeGuestSessions: 'Session хүчингүй болгох',
    invite: 'Урилга илгээх',
    renew: 'Сунгах',
    setClean: 'Цэвэр болгох',
    query: 'Хайх',
  },
  labels: {
    room: 'Өрөө',
    floor: 'Давхар',
    category: 'Ангилал',
    nextBooking: 'Дараагийн захиалга',
    remaining: 'үлдсэн',
    until: 'хүртэл',
    readyNotBefore: 'Бэлэн болох цаг',
    guest: 'Зочин',
    identityType: 'Бичиг баримтын төрөл',
    familyName: 'Овог',
    givenName: 'Нэр',
    dateOfBirth: 'Төрсөн огноо',
    nationality: 'Иргэншил',
    registrationNumber: 'Регистрийн дугаар',
    passportNumber: 'Паспортын дугаар',
    documentNumber: 'Бичиг баримтын дугаар',
    issuingCountry: 'Олгосон улс',
    documentType: 'Бичиг баримтын төрөл',
    nights: 'Хоногийн тоо',
    hours: 'Цагийн тоо',
    halfHourUnits: 'Хагас цагийн нэгж',
    unitRate: 'Нэгж үнэ',
    roomCharge: 'Өрөөний төлбөр',
    postCharges: 'Төлбөр бичих',
    lockReport: 'Минибарын тайланг төлбөрт түгжих',
    attemptRef: 'Төлбөрийн оролдлогын дугаар',
    attemptRefHint:
      'Төлбөр бүртгэхдээ ижил дугаарыг provider reference-д бичнэ; тулгахад тайлан хаагдана.',
    reconcileReport: 'Тулгах',
    bookingRef: 'Захиалгын дугаар',
    bookingRefHint: 'Online захиалгатай бол зочны захиалгын дугаар (8–12 тэмдэгт).',
    noOpenShift: 'Бэлэн мөнгө бүртгэхийн тулд эхлээд ээлж нээнэ (ээлжийн хуудас).',
    plannedCheckout: 'Төлөвлөсөн check-out',
    blockers: 'Хориглох шалтгаан',
    depositRequired: 'Барьцаа шаардлагатай',
    charged: 'Нийт хэрэглээ',
    paid: 'Өмнө төлсөн дүн',
    balance: 'Үлдэгдэл',
    channel: 'Төлбөрийн хэлбэр',
    amount: 'Дүн',
    openingCounted: 'Эхний тоолсон бэлэн мөнгө',
    countedCash: 'Тоолсон бэлэн мөнгө',
    expectedCash: 'Байх ёстой бэлэн мөнгө',
    variance: 'Зөрүү',
    startsAt: 'Эрх эхэлсэн',
    expiresAt: 'Эрх дуусах',
    graceUntil: 'Grace period дуусах',
    package: 'Багц',
    term: 'Хугацаа (сар)',
    provider: 'Төлбөрийн үйлчилгээ',
    roles: 'Эрх',
    reason: 'Шалтгаан',
    counted: 'Бодит тоо',
    product: 'Бүтээгдэхүүн',
    quantity: 'Тоо ширхэг',
    requested: 'Хүссэн тоо',
    confirmed: 'Баталсан тоо',
    state: 'Төлөв',
    openedAt: 'Үүссэн',
    month: 'Сар',
    from: 'Эхлэх огноо',
    to: 'Дуусах огноо',
    name: 'Нэр',
  },
  channels: { CASH: 'Бэлэн мөнгө', CARD_MANUAL: 'Гараар бүртгэсэн картын төлбөр', QPAY: 'QPay' },
  identityTypes: {
    MN_REG_NO: 'Монгол регистр',
    FOREIGN_PASSPORT: 'Гадаад паспорт',
    OTHER_GOV_ID: 'Бусад төрийн бичиг баримт',
    NO_DOCUMENT: 'Баримтгүй',
  } as Record<string, string>,
  grace: {
    banner:
      'Subscription-ийн хугацаа дууссан. Grace period дуусах хүртэл бүх багцын эрх хэвийн үргэлжилнэ.',
    lockedTitle: 'Subscription-ийн эрх дууссан',
    locked:
      '48 цагийн grace period дууссан бөгөөд renewal төлбөр баталгаажаагүй тул систем түгжигдсэн. Сунгалтын төлбөр баталгаажсаны дараа эрх сэргэнэ.',
    suspendedTitle: 'Subscription түдгэлзүүлсэн',
    suspended:
      'Эрх бүхий Platform хэрэглэгч subscription-ийг журмын дагуу түр хаасан. Support-той холбогдоно уу.',
    expiringSoon: 'Эрх дуусахад 7 буюу түүнээс цөөн хоног үлдсэн.',
  },
} as const;
